<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <script src="./promise.js"></script>
</head>

<body>
    <script>
        const p=Promise.resolve('ok');
        console.log(p)

        const p2=Promise.resolve(new Promise((resolve,reject)=>{
            //resolve('success');
            reject('error')
        }))
        console.log(p2)

        const p3=Promise.resolve(Promise.resolve('aaa'));
        console.log(p3)


        const p4=Promise.reject('errorp4');
        console.log(p4);

        const p5=Promise.reject(new Promise((resolve,reject)=>{
            resolve('eee5')
        }))
        console.log(p5);
        // let p = new Promise((resolve, reject) => {
        //     // reject('ee');
        //     // resolve('ok');

        //     //抛出異常
        //     // throw "error";

        //     //異步狀態會跑到pending狀態 執行狀態再進行回調
        //     setTimeout(() => {
        //       resolve('ok')
        //         // reject('ee');
        //    }, 1000)
        // })
        // console.log(p)

        // p.then(value=>{
        //     console.log(value);
        // },reason=>{
        //     console.warn(reason);
        // })



        // p.then(value=>{
        //     alert(value);
        // },reason=>{
        //     alert(reason);
        // })

        // const res = p.then(value => {
        //     console.log(value);
        //     // return 'hello';
        //     // return new Promise((resolve, reject) => {
        //     //     //resolve('success');
        //     //     reject('no')
        //     // })
        //     //拋出異常 就要用try catch
        //    // throw 'eee'
        // }, reason => {
        //     console.warn(reason);

        //    // throw 'eee'
        // })

        // let res=p.catch(reason=>{
        //     console.warn(reason);
        // })
        // console.log(res)

        //setTimeout的關係在第二個就會失敗
        //p.then()值傳遞 如果沒傳值
        // p.then()
        // .then(value=>{
        //     console.log(111);
        //     //throw 'error'
        // }).then(value=>{
        //     console.log(222);
        // }).then(value=>{
        //     console.log(333);
        // }).catch(reason=>{
        //     console.warn(reason);
        // })
    </script>
</body>

</html>